DOMAIN = "actualbudget"
PLATFORM = "sensor"
DOMAIN_DATA = f"{DOMAIN}_data"

DEFAULT_ICON = "mdi:bank"

CONFIG_ENDPOINT = "endpoint"
CONFIG_PASSWORD = "password"
CONFIG_FILE = "file"
CONFIG_UNIT = "unit"
CONFIG_PREFIX = "prefix"
CONFIG_CERT = "cert"
CONFIG_SKIP_VALIDATE_CERT = "skip_validate_cert"
CONFIG_ENCRYPT_PASSWORD = "encrypt_password"
ATTR_CONFIG_ENTRY_ID = "config_entry_id"
ATTR_ACCOUNT = "account"
ATTR_DATE = "date"
ATTR_AMOUNT = "amount"
ATTR_PAYEE = "payee"
ATTR_NOTES = "notes"
ATTR_CATEGORY = "category"
ATTR_IMPORTED_ID = "imported_id"
ATTR_CLEARED = "cleared"
ATTR_CONFIRM = "confirm"
